apiVersion: 1

datasources:
- name: PostgreSQL
  type: postgres
  url: postgres:5432
  user: healthpulse
  secureJsonData:
    password: "healthpulsepassword"
  jsonData:
    database: healthpulse
    sslmode: "disable"
    maxOpenConns: 100
    maxIdleConns: 100
    maxIdleConnsTime: 60
    connMaxLifetime: 14400
    postgresVersion: 1400
    timescaledb: false
